language: node_js

node_js:
  - "lts/*"

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target-branch: master
  on:
    branch: source
